services:
  simpleblog:
    build: .
    container_name: simpleblog
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./www:/var/www/html
      - ./db:/var/db
      - ./config:/var/config:ro
    mem_limit: 256m
    memswap_limit: 256m
    read_only: true
    tmpfs:
      - /tmp
      - /var/run
      - /var/lock
      - /var/log/apache2
    networks:
      - default
      - npm_default

networks:
  npm_default:
    external: true
